FROM node:18 as base
# Create app directory
WORKDIR /app
COPY package*.json ./
RUN npm i pm2 --location=global

FROM base as test
RUN npm ci
COPY . .
RUN npm test

FROM base as prod
RUN npm ci --omit=dev
# If you are building your code for production
# RUN npm ci --only=production
COPY . .

#EXPOSE 3001
CMD [ "pm2-runtime", "ecosystem.config.js","--env","production" ]